name: Deploy manual

on: workflow_dispatch
  
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar o checkout
        uses: actions/checkout@v2

      - name: Deploy no heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "gol-soma-actions"
          heroku_email: "landcock84@gmail.com"
          dontuseforce: true

